development:
  adapter: postgresql
  encoding: utf8
  database: github_api_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: github_api_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: github_api
  pool: 5